input: ["img", "bboxes", "bbox_labels", "bbox_scores"]
output: ["obj_attrs", "bboxes", "bbox_labels", "bbox_scores"]

# BoT-SORT configurations (without re-ID).
track_high_thresh: 0.6
track_low_thresh: 0.1
new_track_thresh: 0.7
match_thresh: 0.8
track_buffer: 30
frame_rate: 30

# TODO: Re-ID configurations.
